# Generated by Django 5.2 on 2025-04-21 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0002_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionRecomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soporte_minimo', models.FloatField(default=0.01)),
                ('confianza_minima', models.FloatField(default=0.2)),
                ('lift_minimo', models.FloatField(default=1.0)),
                ('max_recomendaciones', models.PositiveIntegerField(default=5)),
                ('frecuencia_actualizacion_dias', models.PositiveIntegerField(default=7)),
                ('ultima_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReglaAsociacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soporte', models.FloatField(help_text='Frecuencia de aparición del conjunto en el total de transacciones')),
                ('confianza', models.FloatField(help_text='Probabilidad de que el producto recomendado aparezca cuando aparece el origen')),
                ('lift', models.FloatField(help_text='Relación entre la confianza y la frecuencia esperada del producto recomendado')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('producto_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_origen', to='productos.producto')),
                ('producto_recomendado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_recomendado', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Regla de Asociación',
                'verbose_name_plural': 'Reglas de Asociación',
                'ordering': ['-lift', '-confianza'],
                'unique_together': {('producto_origen', 'producto_recomendado')},
            },
        ),
    ]
