# Generated by Django 5.2 on 2025-04-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_imagen'),
        ('recomendaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reglaasociacion',
            index=models.Index(fields=['producto_origen', '-lift', '-confianza'], name='recomendaci_product_ad5eb2_idx'),
        ),
        migrations.AddIndex(
            model_name='reglaasociacion',
            index=models.Index(fields=['producto_recomendado'], name='recomendaci_product_63cde5_idx'),
        ),
    ]
