# Generated by Django 5.2 on 2025-04-21 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_imagen'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoRecomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.FloatField(help_text='Puntuación de confianza en la recomendación')),
                ('soporte', models.FloatField(default=0.0, help_text='Soporte de la regla de asociación')),
                ('lift', models.FloatField(default=1.0, help_text='Lift de la regla (relevancia)')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('producto_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones_origen', to='productos.producto')),
                ('producto_recomendado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones_destino', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Recomendación de Producto',
                'verbose_name_plural': 'Recomendaciones de Productos',
                'ordering': ['-puntuacion'],
                'unique_together': {('producto_origen', 'producto_recomendado')},
            },
        ),
    ]
