# Generated by Django 5.2 on 2025-04-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_productorecomendacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaventa',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
        migrations.DeleteModel(
            name='ProductoRecomendacion',
        ),
    ]
